name: easydevlp
description: A Flutter Package to Make Flutter Devlopment more Easy.
version: 0.0.1
homepage: https://github.com/rohitsangwan01/easydevlp.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get:
  get_storage:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
